/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import model.InvModelTable;
import model.Invoices;


public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        I_Table = new javax.swing.JTable();
        I_Table.getSelectionModel().addListSelectionListener(controller);
        CreateNewInvoice_btn = new javax.swing.JButton();
        CreateNewInvoice_btn.addActionListener(controller);
        DeleteInvoice_btn = new javax.swing.JButton();
        DeleteInvoice_btn.addActionListener(controller);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InvoiceNum_lbl = new javax.swing.JLabel();
        InvoiceDate_lbl = new javax.swing.JLabel();
        CustomerName_lbl = new javax.swing.JLabel();
        InvoicTotal_lbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        L_Table = new javax.swing.JTable();
        CreateNewItem_btn = new javax.swing.JButton();
        CreateNewItem_btn.addActionListener(controller);
        Delete_btn = new javax.swing.JButton();
        Delete_btn.addActionListener(controller);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadFileItem = new javax.swing.JMenuItem();
        LoadFileItem.addActionListener(controller);
        SaveFileItem = new javax.swing.JMenuItem();
        SaveFileItem.addActionListener(controller);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        I_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(I_Table);

        CreateNewInvoice_btn.setText("Create New Invoice");

        DeleteInvoice_btn.setText("Delete Invoice");

        jLabel1.setText("Invoice Number");

        jLabel2.setText("Invoice Date");

        jLabel3.setText("Customer Name");

        jLabel4.setText("Invoice Total");

        L_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(L_Table);

        CreateNewItem_btn.setText("CreateNewItem");

        Delete_btn.setText("DeleteItem");

        jMenu1.setText("File");

        LoadFileItem.setText("Load File");
        jMenu1.add(LoadFileItem);

        SaveFileItem.setText("save File");
        jMenu1.add(SaveFileItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(CreateNewInvoice_btn)
                        .addGap(79, 79, 79)
                        .addComponent(DeleteInvoice_btn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InvoicTotal_lbl)
                                    .addComponent(CustomerName_lbl)
                                    .addComponent(InvoiceDate_lbl)
                                    .addComponent(InvoiceNum_lbl)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(CreateNewItem_btn)
                        .addGap(106, 106, 106)
                        .addComponent(Delete_btn)))
                .addGap(0, 230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateNewInvoice_btn)
                            .addComponent(DeleteInvoice_btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(InvoiceNum_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InvoiceDate_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CustomerName_lbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(InvoicTotal_lbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateNewItem_btn)
                            .addComponent(Delete_btn))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNewInvoice_btn;
    private javax.swing.JButton CreateNewItem_btn;
    private javax.swing.JLabel CustomerName_lbl;
    private javax.swing.JButton DeleteInvoice_btn;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JTable I_Table;
    private javax.swing.JLabel InvoicTotal_lbl;
    private javax.swing.JLabel InvoiceDate_lbl;
    private javax.swing.JLabel InvoiceNum_lbl;
    private javax.swing.JTable L_Table;
    private javax.swing.JMenuItem LoadFileItem;
    private javax.swing.JMenuItem SaveFileItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
private ArrayList<Invoices> invoicess;
private  Controller controller=new Controller(this);
private InvModelTable InvTableModel;

    public ArrayList<Invoices> getInvoicess() {
        return invoicess;
    }

    public void setInvoicess(ArrayList<Invoices> invoicess) {
        this.invoicess = invoicess;
    }

    public InvModelTable getInvTableModel() {
        return InvTableModel;
    }

    public void setInvTableModel(InvModelTable InvTableModel) {
        this.InvTableModel = InvTableModel;
    }

    public JTable getI_Table() {
        return I_Table;
    }

   

    public JLabel getCustomerName_lbl() {
        return CustomerName_lbl;
    }

    

    public JLabel getInvoicTotal_lbl() {
        return InvoicTotal_lbl;
    }

    

    public JLabel getInvoiceNum_lbl() {
        return InvoiceNum_lbl;
    }

   
    public JTable getL_Table() {
        return L_Table;
    }

  
    

    public Controller getController() {
        return controller;
    }

    
    public JLabel getInvoiceDate_lbl() {
        return InvoiceDate_lbl;
    }

   

    public int getNextInvNum(){
    int num=0;
    for(Invoices invoice:invoicess){
    if(invoice.getNumber()>num)
        num=invoice.getNumber();
    }
    return ++num;
    
    }

    


}
